export const SET_STAVE_FIELD = 'SET_STAVE_FIELD';
export const SET_FIELD = 'SET_FIELD';
export const SET_CLEF = 'SET_CLEF';
export const ADD_NOTE_TO_VOICE = 'ADD_NOTE_TO_VOICE';
export const ADD_NOTE_TO_STAVE = 'ADD_NOTE_TO_STAVE';
export const DELETE_NOTE_FROM_VOICE = 'DELETE_NOTE_FROM_VOICE';
export const DELETE_NOTE_FROM_STAVE = 'DELETE_NOTE_FROM_STAVE';
